### ISSUE TITLE
Websocket support

### ISSUE THREAD

**Issue by IDerr** [PythiaSocialTech/sirqle#3]
Hello ! 

Thanks a lot for your project, by curiosity, will you support the websocket client for surrealdb ?

Thanks a lot

**Comment by TudorAndrei** [comment]
@IDerr Hey, we're adding the support for websockets soon. It should be available in less than a week, from today. Sorry for the late answer, but we're having issues with notifications :sweat_smile:

**Comment by TudorAndrei-Pythia** [comment]
@IDerr  Hey, we're adding the support for websockets soon. It should be available in less than a week, from today. Sorry for the late answer, but we're having issues with notifications sweat_smile

**Comment by IDerr** [comment]
No worries! Thanks for the notification!

**Comment by TudorAndrei-Pythia** [comment]
I added support in 9c9f1f7c7a8b8050ffa1eeab797b72041a4e463b.
Let me know how it works for you :smile:
